---
- name: Install required packages
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
    cache_valid_time: 3600

- name: Add nodejs keyring to gpg
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280

- name: Add nodejs repository
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/{{ NODE_VERSION }} {{ ansible_distribution_release }} main

- name: Install nodejs
  become: yes
  apt:
    cache_valid_time: 3600
    name: nodejs
    state: present
